# Generated by Django 2.1.7 on 2019-07-15 11:36

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('article_id', models.CharField(max_length=10)),
                ('content', ckeditor.fields.RichTextField()),
                ('description', ckeditor.fields.RichTextField()),
                ('type', models.CharField(default='个人日记', max_length=10)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudyDiary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('article_id', models.CharField(max_length=10)),
                ('content', ckeditor.fields.RichTextField()),
                ('description', ckeditor.fields.RichTextField()),
                ('type', models.CharField(default='学习笔记', max_length=10)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
