# Generated by Django 2.1.7 on 2019-07-19 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Userinfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('level', models.CharField(max_length=2)),
                ('parent', models.IntegerField(default=None)),
                ('content', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Userinfo.UserInfo')),
            ],
        ),
    ]
