# Generated by Django 2.1.7 on 2019-07-22 08:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Leaveword', '0003_auto_20190722_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessage',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 22, 16, 36, 40, 607851)),
        ),
    ]
