# Generated by Django 2.1.7 on 2019-07-22 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Leaveword', '0004_usermessage_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermessage',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
